import Link from "next/link";
import MenuBar from "./util/menu";

const models = [
  { name: "alala", imgSrc: "/_alala_.png" },
  { name: "maksim", imgSrc: "/_maksimi_.png" },
  { name: "mercelina", imgSrc: "/_mercelina_.png" },
  { name: "lovelyen", imgSrc: "/_lovelyen.png" },
  { name: "o0o", imgSrc: "/_o0o__.png" },
  { name: "witch", imgSrc: "/_witch__.png" },
  { name: "m8a8ytip", imgSrc: "/8a8ytip.png" },
  { name: "aarilaviee", imgSrc: "/aarilaviee.png" },
  { name: "acemorton", imgSrc: "/ace_morton.png" },
  { name: "ainaschavell", imgSrc: "/ainaschavell.png" },
  { name: "aio_lovee", imgSrc: "/aio_lovee.png" },
  { name: "akaikoneko", imgSrc: "/akai_koneko.png" },
  { name: "alicebels", imgSrc: "/alicebels.png" },
  { name: "allotropp", imgSrc: "/allotropp.png" },
  { name: "amazongirls", imgSrc: "/amazongirls.png" },
  { name: "amelia_star20", imgSrc: "/amelia_star20.png" },
  { name: "amelia_sweetyy", imgSrc: "/amelia_sweetyy.png" },
  { name: "amina_artin", imgSrc: "/amina_artin.png" },
  { name: "anabel054", imgSrc: "/anabel054.png" },
  { name: "angelawalton", imgSrc: "/angelawalton.png" },
  { name: "anita_richh", imgSrc: "/anita_richh.png" },
  { name: "anitarossi__", imgSrc: "/anitarossi__.png" },
  { name: "anni_lovely", imgSrc: "/anni_lovely.png" },
  { name: "annie_shyy", imgSrc: "/annie_shyy.png" },
  { name: "anniehillofficial_", imgSrc: "/anniehillofficial_.png" },
  { name: "ashlyeroberts01", imgSrc: "/ashlyeroberts01.png" },
  { name: "asianangel1", imgSrc: "/asianangel1.png" },
  { name: "babyroxynill", imgSrc: "/babyroxynill.png" },
  { name: "britneycolins", imgSrc: "/britneycolins.png" },
  { name: "bugsbunnyb", imgSrc: "/bugsbunnyb.png" },
  { name: "caroline_oop1", imgSrc: "/caroline_oop1.png" },
  { name: "carolinefoxxx", imgSrc: "/carolinefoxxx.png" },
  { name: "cherry_tery", imgSrc: "/cherry_tery.png" },
  { name: "chloe_catherine_mykers", imgSrc: "/chloe_catherine_mykers.png" },
  { name: "cielo69", imgSrc: "/cielo69_.png" },
  { name: "cleo_one", imgSrc: "/cleo_one.png" },
  { name: "cosmic_boobs", imgSrc: "/cosmic_boobs.png" },
  { name: "crystalblush", imgSrc: "/crystalblush.png" },
  { name: "cute_caprice", imgSrc: "/cute_caprice.png" },
  { name: "deniseone", imgSrc: "/deniseone.png" },
  { name: "di_huny", imgSrc: "/di_huny.png" },
  { name: "dirtygirls99", imgSrc: "/dirtygirls99.png" },
  { name: "domenikka", imgSrc: "/domenikka.png" },
  { name: "efulia_wood", imgSrc: "/efulia_wood.png" },
  { name: "elizabeth_gray", imgSrc: "/elizabeth_gray.png" },
  { name: "ellie_leen", imgSrc: "/ellie_leen.png" },
  { name: "emily_blush", imgSrc: "/emily_blush.png" },
  { name: "emilyn_keatting", imgSrc: "/emilyn_keatting.png" },
  { name: "emma_lu1", imgSrc: "/emma_lu1.png" },
  { name: "felissiany", imgSrc: "/felissiany.png" },
  { name: "gigisquirty", imgSrc: "/gigisquirty.png" },
  { name: "girl_of_yourdreams", imgSrc: "/girl_of_yourdreams_.png" },
  { name: "golden_bag", imgSrc: "/golden_bag.png" },
  { name: "grase_daves", imgSrc: "/grase_daves.png" },
  { name: "harubunny", imgSrc: "/harubunny.png" },
  { name: "hee_jin", imgSrc: "/hee_jin.png" },
  { name: "hemi_lou", imgSrc: "/hemi_lou.png" },
  { name: "hersheys_aran", imgSrc: "/hersheys_aran.png" },
  { name: "hi_popsy", imgSrc: "/hi_popsy.png" },
  { name: "hollyextra", imgSrc: "/hollyextra.png" },
  { name: "honey_devildoll", imgSrc: "/honey_devildoll.png" },
  { name: "iminako", imgSrc: "/iminako.png" },
  { name: "intim_mate", imgSrc: "/intim_mate.png" },
  { name: "intrigueeme", imgSrc: "/intrigueeme.png" },
  { name: "ive_kitsun", imgSrc: "/ive_kitsun.png" },
  { name: "izumi_ross", imgSrc: "/izumi_ross.png" },
  { name: "jeezy_jool", imgSrc: "/jeezy_jool.png" },
  { name: "jilly_wolly1", imgSrc: "/jilly_wolly1.png" },
  { name: "jitoon_exe", imgSrc: "/jitoon_exe.png" },
  { name: "josephinejackson", imgSrc: "/josephinejackson.png" },
  { name: "juicy_mel", imgSrc: "/juicy_mel.png" },
  { name: "just_jenifer", imgSrc: "/just_jenifer.png" },
  { name: "karenaudrey", imgSrc: "/karenaudrey.png" },
  { name: "katecynthia", imgSrc: "/katecynthia.png" },
  { name: "katya1337", imgSrc: "/katya1337.png" },
  { name: "kebeshka", imgSrc: "/kebeshka.png" },
  { name: "buttybae", imgSrc: "/buttybae.png" },
  { name: "keylalong", imgSrc: "/keylalong.png" },
  { name: "kikiloves_you", imgSrc: "/kikiloves_you.png" },
  { name: "kitttycat_meow", imgSrc: "/kitttycat_meow.png" },
  { name: "lana_kane", imgSrc: "/lana_kane_.png" },
  { name: "lana_sky", imgSrc: "/lana_sky.png" },
  { name: "laura_lee", imgSrc: "/laura_lee.png" },
  { name: "lezyliza", imgSrc: "/lezyliza.png" },
  { name: "lianayun", imgSrc: "/lianayun.png" },
  { name: "lika_moon", imgSrc: "/lika_moon.png" },
  { name: "lil_istar", imgSrc: "/lil_istar.png" },
  { name: "lilemma", imgSrc: "/lilemma.png" },
  { name: "lili_and_niki", imgSrc: "/lili_and_niki.png" },
  { name: "lilmollypill", imgSrc: "/lilmollypill.png" },
  { name: "lily_weep", imgSrc: "/lily_weep.png" },
  { name: "little_devil", imgSrc: "/little_devil.png" },
  { name: "lola_and_girls", imgSrc: "/lola_and_girls.png" },
  { name: "lolli_mary", imgSrc: "/lolli_mary.png" },
  { name: "lorrimoon", imgSrc: "/lorrimoon.png" },
  { name: "magicinsidemee", imgSrc: "/magicinsidemee.png" },
  { name: "marti_lovely", imgSrc: "/marti_lovely.png" },
  { name: "mary_shiota", imgSrc: "/mary_shiota.png" },
  { name: "maryperetto", imgSrc: "/maryperetto.png" },
  { name: "megancute2", imgSrc: "/megancute2.png" },
  { name: "melisa_sim", imgSrc: "/melisa_sim.png" },
  { name: "melissa_shawty", imgSrc: "/melissa_shawty.png" },
  { name: "miamaiha", imgSrc: "/miamaiha.png" },
  { name: "michelleysun", imgSrc: "/michelleysun.png" },
  { name: "mika__cute", imgSrc: "/mika__cute.png" },
  { name: "mikachu", imgSrc: "/mikachu.png" },
  { name: "millaava", imgSrc: "/millaava.png" },
  { name: "miss___molly", imgSrc: "/miss___molly.png" },
  { name: "misscharlotte1", imgSrc: "/misscharlotte1.png" },
  { name: "miyakon", imgSrc: "/miyakon.png" },
  { name: "miyakozu", imgSrc: "/miyakozu.png" },
  { name: "mollyroxys", imgSrc: "/mollyroxys.png" },
  { name: "nancy_winter", imgSrc: "/nancy_winter.png" },
  { name: "naughty_bunny1", imgSrc: "/naughty_bunny1.png" },
  { name: "nica_nee", imgSrc: "/nica_nee.png" },
  { name: "niilaa", imgSrc: "/niilaa.png" },
  { name: "nika_konovalova", imgSrc: "/nika_konovalova.png" },
  { name: "nika_lodge", imgSrc: "/nika_lodge.png" },
  { name: "nikagray2", imgSrc: "/nikagray2.png" },
  { name: "nikkymouse", imgSrc: "/nikkymouse.png" },
  { name: "noah_sw", imgSrc: "/noah_sw.png" },
  { name: "oh_honey", imgSrc: "/oh_honey_.png" },
  { name: "oooops", imgSrc: "/oooops__.png" },
  { name: "ori4ka", imgSrc: "/ori4ka.png" },
  { name: "patricia_bloom", imgSrc: "/patricia_bloom.png" },
  { name: "petite_amely", imgSrc: "/petite_amely.png" },
  { name: "petitegirll", imgSrc: "/petitegirll.png" },
  { name: "playnofuckinggames", imgSrc: "/playnofuckinggames.png" },
  { name: "pretty_kujira", imgSrc: "/pretty_kujira.png" },
  { name: "prettykimm", imgSrc: "/prettykimm.png" },
  { name: "rebeccabryan", imgSrc: "/rebeccabryan.png" },
  { name: "renae_tom", imgSrc: "/renae_tom.png" },
  { name: "renessy", imgSrc: "/renessy.png" },
  { name: "riskyproject", imgSrc: "/riskyproject.png" },
  { name: "rocketsgirl", imgSrc: "/rocketsgirl.png" },
  { name: "sakura_himari", imgSrc: "/sakura_himari.png" },
  { name: "sexy_b0rsch", imgSrc: "/sexy_b0rsch.png" },
  { name: "shesnotuwu", imgSrc: "/shesnotuwu.png" },
  { name: "shy_zooe", imgSrc: "/shy_zooe.png" },
  { name: "slaty_sugar", imgSrc: "/slaty_sugar.png" },
  { name: "sparklity", imgSrc: "/sparklity.png" },
  { name: "stephaweb", imgSrc: "/stephaweb.png" },
  { name: "starann", imgSrc: "/starann.png" },
  { name: "sunnyfia", imgSrc: "/sunnyfia.png" },
  { name: "surisoyan", imgSrc: "/surisoyan.png" },
  { name: "sweetmarilynn", imgSrc: "/sweetmarilynn.png" },
  { name: "sweety_rinushka", imgSrc: "/sweety_rinushka.png" },
  { name: "taanni_bc", imgSrc: "/taanni_bc.png" },
  { name: "tama_ye", imgSrc: "/tama_ye.png" },
  { name: "therealbonnieclydex", imgSrc: "/therealbonnieclydex.png" },
  { name: "ur_moment", imgSrc: "/ur_moment.png" },
  { name: "veronica_loo", imgSrc: "/veronica_loo.png" },
  { name: "violetta_111", imgSrc: "/violetta_111.png" },
  { name: "vivien_fox", imgSrc: "/vivien_fox.png" },
  { name: "Wizard", imgSrc: "/Wizard.png" },
  { name: "yamaguchi", imgSrc: "/yamaguchi.png" },
  { name: "your_dolls", imgSrc: "/your_dolls.png" },
  { name: "ysann", imgSrc: "/ysann.png" },
  { name: "yui_mei", imgSrc: "/yui_mei.png" },
  { name: "yummysoap", imgSrc: "/yummysoap.png" },
  { name: "yuna_nam", imgSrc: "/yuna_nam.png" },
  { name: "zoe__0", imgSrc: "/zoe__0.png" },
  { name: "honey_devildoll", imgSrc: "/honey_devildoll.png" },
  { name: "honey_devildoll", imgSrc: "/honey_devildoll.png" },
  { name: "honey_devildoll", imgSrc: "/honey_devildoll.png" },
  { name: "honey_devildoll", imgSrc: "/honey_devildoll.png" },
  { name: "honey_devildoll", imgSrc: "/honey_devildoll.png" },
  { name: "honey_devildoll", imgSrc: "/honey_devildoll.png" },
  { name: "honey_devildoll", imgSrc: "/honey_devildoll.png" },
  { name: "honey_devildoll", imgSrc: "/honey_devildoll.png" },
  { name: "honey_devildoll", imgSrc: "/honey_devildoll.png" },
  { name: "honey_devildoll", imgSrc: "/honey_devildoll.png" },
  { name: "honey_devildoll", imgSrc: "/honey_devildoll.png" },
  { name: "honey_devildoll", imgSrc: "/honey_devildoll.png" },
  { name: "honey_devildoll", imgSrc: "/honey_devildoll.png" },
  { name: "honey_devildoll", imgSrc: "/honey_devildoll.png" },
  { name: "honey_devildoll", imgSrc: "/honey_devildoll.png" },
  { name: "honey_devildoll", imgSrc: "/honey_devildoll.png" },
  { name: "honey_devildoll", imgSrc: "/honey_devildoll.png" },
  { name: "honey_devildoll", imgSrc: "/honey_devildoll.png" },
  { name: "honey_devildoll", imgSrc: "/honey_devildoll.png" },
  { name: "honey_devildoll", imgSrc: "/honey_devildoll.png" },
  { name: "honey_devildoll", imgSrc: "/honey_devildoll.png" },
  { name: "honey_devildoll", imgSrc: "/honey_devildoll.png" },
  { name: "honey_devildoll", imgSrc: "/honey_devildoll.png" },
  { name: "honey_devildoll", imgSrc: "/honey_devildoll.png" },
  { name: "honey_devildoll", imgSrc: "/honey_devildoll.png" },
  { name: "honey_devildoll", imgSrc: "/honey_devildoll.png" },
  { name: "honey_devildoll", imgSrc: "/honey_devildoll.png" },
  { name: "honey_devildoll", imgSrc: "/honey_devildoll.png" },
  { name: "honey_devildoll", imgSrc: "/honey_devildoll.png" },
  { name: "honey_devildoll", imgSrc: "/honey_devildoll.png" },
  { name: "honey_devildoll", imgSrc: "/honey_devildoll.png" },
  { name: "honey_devildoll", imgSrc: "/honey_devildoll.png" },
  { name: "honey_devildoll", imgSrc: "/honey_devildoll.png" },
  { name: "honey_devildoll", imgSrc: "/honey_devildoll.png" },
  { name: "honey_devildoll", imgSrc: "/honey_devildoll.png" },
  { name: "honey_devildoll", imgSrc: "/honey_devildoll.png" },
  { name: "honey_devildoll", imgSrc: "/honey_devildoll.png" },

];

const MyComponent = () => {
  return (
    <div>
      <MenuBar />
      <div className="flex flex-wrap mt-20">
        {models.map((model, index) => (
          <Link key={index} href={`/model/${model.name}`} passHref>
            <img
              src={model.imgSrc}
              alt="Model Image"
              className="w-40 h-auto m-4"
            />
          </Link>
        ))}
      </div>
    </div>
  );
};

export default MyComponent;
